export interface ProvaUsuario{
    id: string,
    idAgendamento: string,
    idUsuario: string,
    inicioProva: Date,
    terminoProva?: Date,
    dataDe: Date,
    dataAte: Date,
    nota: number,
    qtdAcertos: number,
    qtdQuestoes: number,
    idProva: string,
    nome: string,
    descricao: string,
    dataProva: Date,
    ativo: boolean,
    idLinha: string,
    idProduto: string,
    nomeLinha: string,
    nomeProduto: string,
    nomeUSuario: string,
    provaRealizada: boolean,
    periodoAtivo: boolean
  }